### ISSUE TITLE
Directory for the store?

### ISSUE THREAD

**Issue by colesnicov** [rhelmus/virtmem#3]
Is it possible to specify a directory on the SD card that I use as a store?

**Comment by rhelmus** [comment]
Hello,

Currently this file is fixed. It's very easy to change it though by editing sd_alloc.h (https://github.com/rhelmus/virtmem/blob/master/virtmem/src/alloc/sd_alloc.h)

**Comment by colesnicov** [comment]
Nice :) :+1:
