### ISSUE TITLE
Dealing with regular pointers?

### ISSUE THREAD

**Issue by vitasam** [rhelmus/virtmem#5]
Hi,
I have some practical question. The [manual ](http://rhelmus.github.io/virtmem/index.html#aWrapping) said: 

> When a regular pointer is wrapped inside a virtual pointer, it can be used as it were a virtual pointer. 
>` int *myptr = vptr.unwrap();`

Can I e.g. increment a regular pointer myptr  in order to access the full range of data from the virtual pointer?  Like 
```
myptr += 100;
int b = *(myptr);
```

**Comment by rhelmus** [comment]
It's been a while, but the [manual suggests so](http://rhelmus.github.io/virtmem/classvirtmem_1_1VPtr.html#add1a395d7e70ace45353f02a4e09fc4d) :)

**Comment by vitasam** [comment]
Ok, thanks!
